
spring:
  application:
    name: bankApp
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:bankdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ''  #DB 비밀번호 빈 문자열로 설정
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations:
  - mapper/*.xml
  
server:
  port: 8080
  servlet: 
    encoding:
      charset: utf-8
      force: true
logging:
  logback:
    rollingpolicy:
      max-file-size: 10M
  file:
    path: ./logs
    name: app-prod

  